use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "proxy_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_id: String,
    pub connection_id: String,
    pub request_start_ts: String,
    pub request_end_ts: String,
    pub duration_ms: i64,
    pub client_ip: Option<String>,
    pub client_port: Option<i32>,
    pub proxy_local_ip: Option<String>,
    pub proxy_local_port: Option<i32>,
    pub frontend_server_name: Option<String>,
    pub frontend_http_version: Option<String>,
    pub frontend_scheme: String,
    pub backend_url: String,
    pub backend_host: String,
    pub backend_ip: Option<String>,
    pub backend_port: Option<i32>,
    pub backend_http_version: Option<String>,
    pub upstream_connection_reused: Option<bool>,
    pub method: String,
    pub authority: Option<String>,
    pub path: String,
    pub query: Option<String>,
    pub request_headers_json: String,
    pub request_cookie_header: Option<String>,
    pub request_cookies_json: Option<String>,
    pub request_content_length: Option<i64>,
    pub request_transfer_encoding: Option<String>,
    pub request_content_type: Option<String>,
    pub request_body_sha256: Option<String>,
    pub request_body_preview_base64: Option<String>,
    pub request_body_truncated: Option<bool>,
    pub status_code: Option<i32>,
    pub reason_phrase: Option<String>,
    pub response_headers_json: Option<String>,
    pub response_set_cookie_json: Option<String>,
    pub response_content_length: Option<i64>,
    pub response_transfer_encoding: Option<String>,
    pub response_content_type: Option<String>,
    pub response_content_encoding: Option<String>,
    pub response_body_sha256: Option<String>,
    pub response_body_preview_base64: Option<String>,
    pub response_body_truncated: Option<bool>,
    pub frontend_tls_version: Option<String>,
    pub frontend_tls_cipher_suite: Option<String>,
    pub frontend_tls_alpn: Option<String>,
    pub frontend_tls_sni: Option<String>,
    pub frontend_tls_ja3: Option<String>,
    pub frontend_tls_ja4: Option<String>,
    pub backend_tls_version: Option<String>,
    pub backend_tls_cipher_suite: Option<String>,
    pub backend_tls_alpn: Option<String>,
    pub backend_tls_sni: Option<String>,
    pub backend_cert_leaf_sha256: Option<String>,
    pub backend_cert_subject: Option<String>,
    pub backend_cert_issuer: Option<String>,
    pub backend_cert_not_before: Option<String>,
    pub backend_cert_not_after: Option<String>,
    pub dns_duration_ms: Option<i64>,
    pub connect_duration_ms: Option<i64>,
    pub tls_handshake_duration_ms: Option<i64>,
    pub upstream_first_byte_ms: Option<i64>,
    pub response_stream_duration_ms: Option<i64>,
    pub error_kind: Option<String>,
    pub error_text: Option<String>,
    pub proxy_result: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
